spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ????
    password: ????
    url: jdbc:mysql://localhost:3306/????

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true